package com.ideaforge.ideaforge_backend.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Stores a detected web mention that matches a keyword watch.
 * Generated by the daily scheduled keyword scan.
 */
@Entity
@Table(name = "keyword_alerts", indexes = {
        @Index(name = "idx_ka_user_id",  columnList = "user_id"),
        @Index(name = "idx_ka_watch_id", columnList = "watch_id")
})
@Getter @Setter
@NoArgsConstructor @AllArgsConstructor @Builder
public class KeywordAlert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The keyword watch entry that triggered this alert. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "watch_id", nullable = false)
    private KeywordWatch watch;

    /** The user (owner) who should receive this alert. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** The keyword that matched. */
    @Column(name = "matched_keyword", nullable = false, length = 100)
    private String matchedKeyword;

    /** URL of the source article / page where the keyword was found. */
    @Column(name = "source_url", length = 500)
    private String sourceUrl;

    /** Title of the source article / page. */
    @Column(name = "source_title", length = 300)
    private String sourceTitle;

    @Column(name = "detected_at", nullable = false)
    @Builder.Default
    private LocalDateTime detectedAt = LocalDateTime.now();

    /** False until the owner reads/dismisses the alert. */
    @Column(name = "is_read", nullable = false)
    @Builder.Default
    private Boolean isRead = false;
}
